yml

diff --git a/.github/workflows/27120_test.yml b/.github/workflows/27120_test.yml
--- a/.github/workflows/27120_test.yml
+++ b/.github/workflows/27120_test.yml
@@ -1,4 +1,4 @@
-name: CMake on a single platform
+name: CMake
 
 on:
   push:
@@ -8,41 +8,74 @@ env:
   BUILD_TYPE: Release
 
 jobs:
-
-  build_and_test:
-    runs-on: ${{ matrix.os }} 
+  check_test_file:
+    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [windows-latest] 
+        os: [ubuntu-latest, windows-latest, macos-latest]
     steps:
-      - uses: actions/checkout@v3
+    - name: Checkout repository
+      uses: actions/checkout@v3
 
-      - name: Install CMake
-        run: choco install cmake
+    - name: Check if test script exists
+      shell: bash
+      run: |
+        if [ ! -f "test.cpp" ]; then
+          echo "Test file not found" > napaka.txt
+        fi
 
-      - name: Configure CMake
-        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}
+  build_and_test:
+    needs: check_test_file  
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+    steps:
+    - uses: actions/checkout@v3
 
-      - name: Build
-        run: |
-          echo "Current working directory: $(pwd)"
-          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
+    - name: Check for errors
+      shell: bash
+      run: |
+        if [ -f "napaka.txt" ]; then
+          if [ "$(cat napaka.txt)" = "Test file not found" ]; then
+            echo "Napaka: Test file not found"
+            exit 1
+          fi
+        fi
 
-      - name: Compile Main
-        run: g++ main.cpp test.cpp -o build/main
+    - name: Install CMake
+      shell: bash
+      run: |
+        if [ "$RUNNER_OS" == "Windows" ]; then
+          choco install cmake
+        elif [ "$RUNNER_OS" == "Linux" ]; then
+          sudo apt-get update && sudo apt-get install -y cmake g++
+        else
+          brew install cmake
+        fi
 
-      - name: Run first test
-        run: |
+    - name: Configure CMake
+      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}
+
+    - name: Build
+      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+
+    - name: Compile Main
+      run: g++ main.cpp test.cpp -o build/main
+
+    - name: Run first test
+      shell: bash
+      run: |
+          if [ "${RUNNER_OS}" == "Windows" ]; then
             ${{github.workspace}}/build/main test_kmp "znanstveniki" ${{github.workspace}}\cmake-build-debug\test-besedilo.txt
-      
-      - name: Print current directory path and list directories
-        shell: bash
-        run: |
-            echo "Trenutna pot: $(pwd)"
-            echo "Mape v trenutni poti:"
-            ls -d */
+          else 
+           ${{github.workspace}}/build/main test_kmp "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
+         
 
-            
-
-
-            
+    - name: Run second test
+      shell: bash
+      run: |
+          if [ "${RUNNER_OS}" == "Windows" ]; then
+            ${{github.workspace}}/build/main test_kmp "znanstveniki" ${{github.workspace}}\cmake-build-debug\test-besedilo.txt
+          else 
+            ${{github.workspace}}/build/main test_sunday "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
